import type { InstitutionCatalogItem, KnownLocation } from "./report-ai";

export const guestKnownLocations: KnownLocation[] = [
  ["Kampala", "kampala", "city", "Kampala"],
  ["Ntinda", "ntinda", "neighborhood", "Kampala"],
  ["Nakawa", "nakawa", "division", "Kampala"],
  ["Makindye", "makindye", "division", "Kampala"],
  ["Rubaga", "rubaga", "division", "Kampala"],
  ["Kawempe", "kawempe", "division", "Kampala"],
  ["Kira", "kira", "municipality", "Wakiso"],
  ["Entebbe", "entebbe", "city", "Wakiso"],
  ["Wakiso", "wakiso", "district", "Wakiso"],
  ["Mukono", "mukono", "city", "Mukono"],
  ["Jinja", "jinja", "city", "Jinja"],
  ["Mbarara", "mbarara", "city", "Mbarara"],
  ["Gulu", "gulu", "city", "Gulu"],
  ["Mbale", "mbale", "city", "Mbale"],
  ["Fort Portal", "fort portal", "city", "Kabarole"],
  ["Masaka", "masaka", "city", "Masaka"],
  ["Lira", "lira", "city", "Lira"],
].map(([name, normalized_name, location_type, district_name]) => ({
  name,
  normalized_name,
  location_type,
  district_name,
  region_name: null,
  location_aliases: [],
}));

export const guestInstitutionCatalog: InstitutionCatalogItem[] = [
  {
    id: "uganda-police-force",
    name: "Uganda Police Force",
    short_name: "Uganda Police",
    slug: "uganda-police-force",
    sector: "Security and emergency services",
    description: "Crime reporting, public safety, traffic policing, fire and emergency response.",
    contact_phone: "0800 199 699",
    emergency_phone: "999 / 112; Fire and Rescue 0800 121 222",
    routing_keywords: ["police", "crime", "robbery", "theft", "burglary", "assault", "violence", "missing person", "traffic crash", "fire", "stolen"],
    institution_services: [{
      name: "Crime and public-safety report",
      category_key: "security_incident",
      description: "Crime, theft, violence, traffic incidents, missing persons and urgent public-safety matters.",
      routing_keywords: ["crime", "theft", "robbery", "assault", "violence", "missing", "stolen", "traffic", "fire"],
      required_fields: ["location", "incident_time", "safety_status"],
    }],
  },
  {
    id: "mtn-uganda",
    name: "MTN Uganda Limited",
    short_name: "MTN Uganda",
    slug: "mtn-uganda",
    sector: "Telecommunications",
    description: "Mobile network, internet, airtime, data and MTN Mobile Money services.",
    routing_keywords: ["mtn", "momo", "mobile money", "airtime", "data bundle", "sim card", "network"],
    institution_services: [
      {
        name: "Mobile network and airtime",
        category_key: "telecom_service",
        description: "Airtime, data bundle, SIM, coverage and mobile network complaints.",
        routing_keywords: ["airtime", "data", "bundle", "sim", "network", "coverage", "calls", "sms"],
        required_fields: ["affected_phone_number", "approximate_time"],
      },
      {
        name: "MTN Mobile Money",
        category_key: "mobile_money",
        description: "Transfers, cash-in, cash-out, reversals, fraud and wallet complaints.",
        routing_keywords: ["momo", "mobile money", "transfer", "withdrawal", "deposit", "reversal", "merchant"],
        required_fields: ["transaction_reference", "amount", "transaction_time"],
      },
    ],
  },
  {
    id: "airtel-uganda",
    name: "Airtel Uganda Limited",
    short_name: "Airtel Uganda",
    slug: "airtel-uganda",
    sector: "Telecommunications",
    description: "Mobile network, internet, airtime, data and Airtel Money services.",
    routing_keywords: ["airtel", "airtel money", "airtime", "data bundle", "sim card", "network"],
    institution_services: [
      {
        name: "Mobile network and airtime",
        category_key: "telecom_service",
        description: "Airtime, data bundle, SIM, coverage and mobile network complaints.",
        routing_keywords: ["airtime", "data", "bundle", "sim", "network", "coverage", "calls", "sms"],
        required_fields: ["affected_phone_number", "approximate_time"],
      },
      {
        name: "Airtel Money",
        category_key: "mobile_money",
        description: "Transfers, cash-in, cash-out, reversals, fraud and wallet complaints.",
        routing_keywords: ["airtel money", "mobile money", "transfer", "withdrawal", "deposit", "reversal", "merchant"],
        required_fields: ["transaction_reference", "amount", "transaction_time"],
      },
    ],
  },
  {
    id: "nwsc-uganda",
    name: "National Water and Sewerage Corporation",
    short_name: "NWSC",
    slug: "nwsc-uganda",
    sector: "Water and sanitation",
    description: "Public water supply, sewerage, billing, leaks and service interruption support.",
    routing_keywords: ["nwsc", "water", "water meter", "sewerage", "water bill", "no water", "pipe burst", "leak"],
    institution_services: [{
      name: "Water and sewerage service",
      category_key: "water_service",
      description: "Water outages, low pressure, leaks, pipe bursts, billing, meters and sewerage.",
      routing_keywords: ["no water", "water outage", "water meter", "leak", "pipe burst", "low pressure", "sewer", "water bill"],
      required_fields: ["location", "customer_reference"],
    }],
  },
  {
    id: "uedcl-uganda",
    name: "Uganda Electricity Distribution Company Limited",
    short_name: "UEDCL",
    slug: "uedcl-uganda",
    sector: "Electricity",
    description: "Electricity distribution, connections, meters, billing and outage response.",
    routing_keywords: ["uedcl", "electricity", "power", "yaka", "meter", "transformer", "blackout", "outage"],
    institution_services: [{
      name: "Electricity distribution",
      category_key: "electricity_service",
      description: "Outages, Yaka, meters, transformers, connections and electricity bills.",
      routing_keywords: ["blackout", "no power", "outage", "yaka", "meter", "transformer", "pole", "electricity bill"],
      required_fields: ["location", "account_or_meter_number"],
    }],
  },
  {
    id: "nira-uganda",
    name: "National Identification and Registration Authority",
    short_name: "NIRA",
    slug: "nira-uganda",
    sector: "Identity and civil registration",
    description: "National identification, NIN, national ID cards and birth and death registration.",
    routing_keywords: ["nira", "nin", "national id", "identity card", "id card", "lost id", "stolen id", "missing id", "birth certificate", "death registration", "id replacement"],
    institution_services: [{
      name: "Identity and civil registration",
      category_key: "identity_service",
      description: "National ID, NIN, birth/death registration, replacement and correction.",
      routing_keywords: ["national id", "nin", "id card", "lost id", "stolen id", "missing id", "birth", "death", "replacement", "renewal", "correction"],
      required_fields: ["service_type"],
    }],
  },
  {
    id: "uneb-uganda",
    name: "Uganda National Examinations Board",
    short_name: "UNEB",
    slug: "uneb-uganda",
    sector: "Education and examinations",
    description: "National examinations, results, verification, equating and examination-centre services.",
    routing_keywords: ["uneb", "exam", "examination", "results", "pass slip", "certificate", "candidate"],
    institution_services: [{
      name: "Examinations and results",
      category_key: "examination_service",
      description: "Exam results, verification, equating, certificates and centre services.",
      routing_keywords: ["exam", "results", "pass slip", "candidate", "verification", "equating", "certificate", "centre"],
      required_fields: ["examination_year", "candidate_or_school_details"],
    }],
  },
  {
    id: "nema-uganda",
    name: "National Environment Management Authority",
    short_name: "NEMA",
    slug: "nema-uganda",
    sector: "Environment",
    description: "Environmental regulation, pollution, waste, wetlands and environmental incident reporting.",
    routing_keywords: ["nema", "environment", "pollution", "waste", "wetland", "noise", "toxic"],
    institution_services: [{
      name: "Environmental incident",
      category_key: "environmental_incident",
      description: "Pollution, waste, wetlands and environmental compliance incidents.",
      routing_keywords: ["pollution", "waste", "wetland", "toxic", "noise", "environment damage"],
      required_fields: ["location", "incident_description"],
    }],
  },
  {
    id: "ministry-works-transport-uganda",
    name: "Ministry of Works and Transport",
    short_name: "MoWT",
    slug: "ministry-works-transport-uganda",
    sector: "Roads and transport",
    description: "National roads, bridges, ferries, road safety and transport regulation, including former UNRA functions.",
    routing_keywords: ["ministry of works", "mowt", "unra", "national road", "highway", "bridge", "ferry", "pothole", "road damage"],
    institution_services: [{
      name: "National roads and bridges",
      category_key: "national_road_issue",
      description: "Damage or hazards on national roads, bridges and ferries.",
      routing_keywords: ["pothole", "road damage", "highway", "national road", "bridge", "ferry", "road hazard"],
      required_fields: ["location", "road_name"],
    }],
  },
  {
    id: "bank-of-uganda",
    name: "Bank of Uganda",
    short_name: "BoU",
    slug: "bank-of-uganda",
    sector: "Financial regulation",
    description: "Central bank and regulator for licensed banks and supervised financial institutions.",
    routing_keywords: ["bank of uganda", "bou", "bank regulator", "licensed bank", "financial institution complaint"],
    institution_services: [{
      name: "Financial institution complaint",
      category_key: "financial_regulation",
      description: "Complaints involving licensed banks and supervised financial institutions.",
      routing_keywords: ["bank complaint", "bank fraud", "bank transfer", "financial institution"],
      required_fields: ["financial_institution", "incident_description"],
    }],
  },
  {
    id: "ministry-health-uganda",
    name: "Ministry of Health Uganda",
    short_name: "Ministry of Health",
    slug: "ministry-health-uganda",
    sector: "Public health",
    description: "Public-health alerts, disease prevention, health-programme information and health-system feedback.",
    contact_phone: "+256 417 712 260",
    emergency_phone: "0800 100 066; health alert SMS 6767",
    routing_keywords: ["ministry of health", "public health", "outbreak", "epidemic", "vaccination", "health alert", "disease"],
    institution_services: [{
      name: "Public-health alert and feedback",
      category_key: "public_health",
      description: "Disease alerts, public-health information and national health-system feedback.",
      routing_keywords: ["outbreak", "epidemic", "vaccination", "health alert", "public health", "disease"],
      required_fields: ["location", "symptoms_or_issue"],
    }],
  },
];
