const labels: Record<string, string> = {
  contact_name: "Contact name",
  contact_phone: "Contact phone",
  affected_phone_number: "Affected phone number",
  approximate_time: "Approximate date or time",
  transaction_reference: "Transaction reference",
  amount: "Amount",
  transaction_time: "Transaction date or time",
  location: "Incident location",
  customer_reference: "Customer reference",
  account_or_meter_number: "Account or meter number",
  account_or_reference: "Account or reference",
  service_type: "Service needed",
  information_requested: "Information requested",
  incident_description: "Incident details",
  candidate_name: "Candidate name",
  candidate_index_number: "Candidate index number",
  candidate_or_school_details: "Candidate or school details",
  examination_level: "Examination level",
  examination_year: "Examination year",
  document_issue: "Document issue",
  suspected_contact_number: "Suspected caller or sender number",
  contact_channel: "Contact channel",
  incident_time: "Incident date or time",
  incident_date: "Incident date",
  information_shared: "Information shared",
  financial_loss: "Money lost",
  safety_status: "Immediate safety",
  immediate_safety_status: "Immediate safety",
  current_location: "Current location",
  symptoms_or_issue: "Symptoms or health issue",
  service_or_department: "Service or department",
  practitioner_or_facility: "Practitioner or facility",
  incident_sequence: "What happened",
  impact: "Impact",
  steps_already_taken: "Steps already taken",
  desired_resolution: "Requested resolution",
  evidence_available: "Available evidence",
  people_affected: "People affected",
  facility_name: "Facility name",
  person_or_reference: "Person or reference",
  public_body: "Public body",
  responsible_body: "Responsible body",
  application_reference: "Application reference",
  court_name: "Court",
  case_reference: "Case reference",
  requesting_authority: "Requesting authority",
  product_name: "Product name",
  purchase_location: "Purchase location",
  health_facility: "Health facility",
  district: "District",
  service_needed: "Service needed",
  road_name: "Road or landmark",
  property_taken_or_damaged: "Property taken or damaged",
  assault_or_injury_details: "Injuries and assistance needed",
  missing_person_details: "Missing person details",
  traffic_incident_details: "Traffic incident details",
  fire_incident_details: "Fire incident details",
};

export function intakeFieldLabel(field: string) {
  return labels[field] || field.replaceAll("_", " ").replace(/^\w/, (letter) => letter.toUpperCase());
}
